currloc(tamankota).
hp(85).
items([],questitems,inventory).
items([],consumables,aspal).
items([],consumables,sliperryfloor).
items([],consumables,cleanfloor).
items([],consumables,footpath).
items([],consumables,floor).
items([],consumables,carpet).
items([],consumables,labfloor).
items([],consumables,smallroad).
items([],consumables,wideroad).
items([],consumables,dirtyfloor).
items([],consumables,messyfloor).
items([],consumables,road).
items([],consumables,bloodyfloor).
items([apple],consumables,inventory).
items([shotgun],questitems,guncabinets).
items([baseballbat],questitems,sportstore).
items([aquadest,mortarAndpestle,syringes,alcohol],questitems,drugshelf).
items([coffee,juice],consumables,refrigerator).
items([mangosten],questitems,refrigerator).
items([tokemasnack],consumables,shelf).
items([bugspray,lebarancookie,softdrink],questitems,shelf).
items([mistletoe],questitems,herbs).
items([molotov],questitems,undertable).
items([painkiller],consumables,car).
items([zombiesblood],questitems,car).
items([chocolate,cottoncandy],consumables,table).
itemcnt(1).
sq1(0).
story(2).
