currloc(lab).
hp(50).
items([],questitems,inventory).
items([],consumables,bloodyfloor).
items([apple],consumables,inventory).
items([chocolate,cottoncandy],consumables,table).
itemcnt(1).
sq1(0).
story(0).
